require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AutomationToolsController do

  # This should return the minimal set of attributes required to create a valid
  # AutomationTool. As you add validations to AutomationTool, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AutomationToolsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all automation_tools as @automation_tools" do
      automation_tool = AutomationTool.create! valid_attributes
      get :index, {}, valid_session
      assigns(:automation_tools).should eq([automation_tool])
    end
  end

  describe "GET show" do
    it "assigns the requested automation_tool as @automation_tool" do
      automation_tool = AutomationTool.create! valid_attributes
      get :show, {:id => automation_tool.to_param}, valid_session
      assigns(:automation_tool).should eq(automation_tool)
    end
  end

  describe "GET new" do
    it "assigns a new automation_tool as @automation_tool" do
      get :new, {}, valid_session
      assigns(:automation_tool).should be_a_new(AutomationTool)
    end
  end

  describe "GET edit" do
    it "assigns the requested automation_tool as @automation_tool" do
      automation_tool = AutomationTool.create! valid_attributes
      get :edit, {:id => automation_tool.to_param}, valid_session
      assigns(:automation_tool).should eq(automation_tool)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AutomationTool" do
        expect {
          post :create, {:automation_tool => valid_attributes}, valid_session
        }.to change(AutomationTool, :count).by(1)
      end

      it "assigns a newly created automation_tool as @automation_tool" do
        post :create, {:automation_tool => valid_attributes}, valid_session
        assigns(:automation_tool).should be_a(AutomationTool)
        assigns(:automation_tool).should be_persisted
      end

      it "redirects to the created automation_tool" do
        post :create, {:automation_tool => valid_attributes}, valid_session
        response.should redirect_to(AutomationTool.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved automation_tool as @automation_tool" do
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationTool.any_instance.stub(:save).and_return(false)
        post :create, {:automation_tool => {}}, valid_session
        assigns(:automation_tool).should be_a_new(AutomationTool)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationTool.any_instance.stub(:save).and_return(false)
        post :create, {:automation_tool => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested automation_tool" do
        automation_tool = AutomationTool.create! valid_attributes
        # Assuming there are no other automation_tools in the database, this
        # specifies that the AutomationTool created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AutomationTool.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => automation_tool.to_param, :automation_tool => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested automation_tool as @automation_tool" do
        automation_tool = AutomationTool.create! valid_attributes
        put :update, {:id => automation_tool.to_param, :automation_tool => valid_attributes}, valid_session
        assigns(:automation_tool).should eq(automation_tool)
      end

      it "redirects to the automation_tool" do
        automation_tool = AutomationTool.create! valid_attributes
        put :update, {:id => automation_tool.to_param, :automation_tool => valid_attributes}, valid_session
        response.should redirect_to(automation_tool)
      end
    end

    describe "with invalid params" do
      it "assigns the automation_tool as @automation_tool" do
        automation_tool = AutomationTool.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationTool.any_instance.stub(:save).and_return(false)
        put :update, {:id => automation_tool.to_param, :automation_tool => {}}, valid_session
        assigns(:automation_tool).should eq(automation_tool)
      end

      it "re-renders the 'edit' template" do
        automation_tool = AutomationTool.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationTool.any_instance.stub(:save).and_return(false)
        put :update, {:id => automation_tool.to_param, :automation_tool => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested automation_tool" do
      automation_tool = AutomationTool.create! valid_attributes
      expect {
        delete :destroy, {:id => automation_tool.to_param}, valid_session
      }.to change(AutomationTool, :count).by(-1)
    end

    it "redirects to the automation_tools list" do
      automation_tool = AutomationTool.create! valid_attributes
      delete :destroy, {:id => automation_tool.to_param}, valid_session
      response.should redirect_to(automation_tools_url)
    end
  end

end
